@startuml GamixWebsite
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0

!include ICONURL/devicons/java.puml
!include ICONURL/devicons2/nextjs_original.puml
!include ICONURL/devicons2/nginx_original.puml
!include ICONURL/devicons2/mysql.puml

Container(website, "Website", "NextJS", "Versão otimizada para web com todos os recursos existentes no aplicativo mobile.", $sprite="nextjs_original")
Container(mobile, "Mobile APP", "NextJS", "Produto pensado e otimizado para o mobile", $sprite="nextjs_original")
System_Boundary(software, "API") {

}

@enduml